const express = require('express');
const router = express.Router();
const crypto = require('crypto');
const nodemailer = require('nodemailer');

// Mock memory store tracking active token links
const activeSignatureLinks = new Map();

router.post('/api/request-signature', async (req, res) => {
  try {
    const { signerEmail, documentId } = req.body;

    if (!signerEmail || !documentId) {
      return res.status(400).json({ error: 'Missing required field parameters' });
    }

    // 1. Generate a secure random token link
    const signatureToken = crypto.randomBytes(32).toString('hex');
    
    // 2. Save link data context into memory mapping arrays
    activeSignatureLinks.set(signatureToken, {
      documentId,
      signerEmail,
      status: 'pending',
      createdAt: new Date()
    });

    // 3. Formulate the external public signature landing URL
    const publicSignatureLink = `http://localhost:5173/public-sign/${signatureToken}`;

    // 4. Create an automatic on-the-fly test account with Ethereal Email
    const testAccount = await nodemailer.createTestAccount();

    const transporter = nodemailer.createTransport({
      host: "smtp.ethereal.email",
      port: 587, // Standard secure submission port that bypasses network blocks
      secure: false, 
      auth: {
        user: testAccount.user, 
        pass: testAccount.pass, 
      },
    });

    // 5. Structure the email payload object mapping
    const mailOptions = {
      from: '"DocuSign Clone Portal" <noreply@docusignclone.com>',
      to: signerEmail,
      subject: 'Signature Request: You have a document waiting to be signed',
      html: `
        <div style="font-family: sans-serif; padding: 30px; border: 1px solid #e2e8f0; border-radius: 8px; max-width: 500px; margin: 0 auto; background-color: #ffffff;">
          <h3 style="color: #0f172a; margin-top: 0;">Document Signature Request</h3>
          <p style="color: #475569; font-size: 14px; line-height: 1.6;">You have been requested to review and sign an official document bundle.</p>
          <p style="color: #475569; font-size: 14px; line-height: 1.6; margin-bottom: 24px;">Click the button below to log in safely and access the drag-and-drop signature canvas:</p>
          <div style="text-align: center; margin-bottom: 24px;">
            <a href="${publicSignatureLink}" style="display: inline-block; padding: 12px 24px; background-color: #007bff; color: white; text-decoration: none; border-radius: 6px; font-weight: bold; font-size: 14px; box-shadow: 0 4px 6px rgba(0,123,255,0.15);">
              Review & Sign Document
            </a>
          </div>
          <p style="margin-top: 30px; font-size: 11px; color: #94a3b8; border-top: 1px solid #f1f5f9; padding-top: 15px; text-align: center;">This public tokenized link is secure and valid for single access authorization.</p>
        </div>
      `
    };

    // Execute transmission
    const info = await transporter.sendMail(mailOptions);

    // Provide the preview URL dynamically generated by Ethereal
    const testPreviewUrl = nodemailer.getTestMessageUrl(info);

    return res.status(200).json({ 
      message: 'Tokenized signature request generated successfully!', 
      publicSignatureLink,
      testPreviewUrl // Passed to frontend so we can see the sent email layout
    });

  } catch (error) {
    console.error('Day 9 Engine Failure:', error);
    return res.status(500).json({ error: 'Server failed to deploy public token links.' });
  }
});

// Endpoint 2: Fetch and validate token links
router.get('/api/validate-token/:token', (req, res) => {
  const { token } = req.params;
  const requestRecord = activeSignatureLinks.get(token);

  if (!requestRecord) {
    return res.status(404).json({ valid: false, error: 'Invalid or expired secure signature token.' });
  }

  return res.status(200).json({ valid: true, data: requestRecord });
});

module.exports = router;
